# Generated by Django 2.2.1 on 2020-07-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20200701_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='razones',
            new_name='comentario',
        ),
    ]
