# Generated by Django 2.2.1 on 2020-07-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
