# Generated by Django 2.2.1 on 2020-07-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200701_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='comentario',
        ),
    ]
